-- AlterEnum
ALTER TYPE "PdfCategory" ADD VALUE IF NOT EXISTS 'POWERPOINT_TEMPLATE';
ALTER TYPE "PdfCategory" ADD VALUE IF NOT EXISTS 'CPD_MATERIAL';

-- AlterTable
ALTER TABLE "PdfDocument" ADD COLUMN IF NOT EXISTS "mimeType" TEXT;
