-- AlterEnum
ALTER TYPE "ResourceKey" ADD VALUE 'INFORMATION_BOOKLET';
ALTER TYPE "ResourceKey" ADD VALUE 'NEWSLETTER';
ALTER TYPE "ResourceKey" ADD VALUE 'POWERPOINT_TEMPLATE';
ALTER TYPE "ResourceKey" ADD VALUE 'CPD_MATERIAL';
