-- AlterEnum
ALTER TYPE "ResourceKey" ADD VALUE 'COLLECTORS';
ALTER TYPE "ResourceKey" ADD VALUE 'CLINICS';
ALTER TYPE "ResourceKey" ADD VALUE 'VIDEOS';
ALTER TYPE "ResourceKey" ADD VALUE 'STREET_DRUG_SEARCH';
